#!/bin/bash
apt-get install cmake -y
apt-get install screen wget gcc build-essential g++ make -y
wget https://github.com/ambrop72/badvpn/archive/1.999.130.zip
unzip 1.999.130.zip
cd badvpn-1.999.130/
cmake ~/badvpn-1.999.130 -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1
make install
echo "Ejecutando BadVPN en puerto 7300"
badvpn-udpgw --listen-addr 127.0.0.1:7300 > /dev/null &
rm install
echo "Finalizado"
echo "Modulo BadUDP - VPSPack"
